version: '3'

services:
    db:
        image: redis:4.0.9
        hostname: redis
        ports:
            - "6379:6379"
    tomcat1: &was
        environment:
            - JAVA_OPTS=-Dspring.profiles.active=docker -Dfile.encoding=euc-kr
        build: 
            context: .
            args:
                conf: tomcat1/conf
                lib: tomcat1/lib
                warpath: tomcat1/webapps/*.war
            dockerfile: ./DockerfileTomcat
        volumes:
            - ./tomcat1/logs/:/usr/local/tomcat/logs/
    tomcat2:
        <<: *was
        environment:
            - JAVA_OPTS=-Dspring.profiles.active=docker -Dfile.encoding=euc-kr
        build:
            context: .
            args:
                conf: tomcat2/conf
                lib: tomcat2/lib
                warpath: tomcat2/webapps/*.war
            dockerfile: ./DockerfileTomcat
        volumes:
            - ./tomcat2/logs/:/usr/local/tomcat/logs/
    nginx:
        build:
            context: .
            dockerfile: ./DockerfileNginx
            args:
                conf: nginx/conf
        ports: 
            - "8080:8080"
        volumes:
            - ./nginx/logs/:/var/log/nginx/
